//WEB SOCKET
1] WebSocket is a communication protocol that provides full-duplex, bidirectional communication channels over a single TCP connection.
2] It is designed to work over the same ports as HTTP and HTTPS (ports 80 and 443, respectively) and is often used for real-time web applications, 
online gaming, chat applications, and other scenarios where low-latency communication is essential.




// TCP/IP
 1] CONECTION OREIENTED
 2] ESTABLISH CONNECTION BEFORE SENDING DATA 
 3] NO PACKET LOSS
 4] SLOW THAN UDP




 //UDP 
 1] CONNECTION LESS
 2] DIRECTLY SEND PACKETS TO THE RECIEVER ADDRESS
 3] FAST BUT PACKET DELIVERY NOT GURRENTEE
 



