
class parent{

public:



};


class child: public parent{

};



//acess specifier defines the type of class from which we are exporting , the parent class is private or public


classvechile{
     public: stringcolor; 
     intmax_speed; 
     }; 
     
     
     class  car:public vehicle{ 
        
        intnum_gears; }; 
        
        
        class bicycle:public vehicle{ 
            bool is_foldable
             }; 
             
    class truck:public vehicle{ 

        intmax_weight; 
        };