//INTERPRETED LANGUAGE

1] INTERPRETED LANGUAGES ARE LANGUAGES THEY ARE DIRECTLY EXECUTED BY INTERPRETED WITHPUT COMPILATION
2] THEY EXECUTE EACH LINE AND CONVERT IT INTO MACHINE CODE AND EXECUTED 
3] DOES NOT DO SEPRATE COMPILATION 
4] EG PYTHON JS
5] ADVANTAGE - EASY TO WRITE ,DEBUG 


//COMPILED LANGUAGES 

1] COMPILED LANGUAGES ARE TRANSLATED INTO MACHINE CODE BY COMPILER BEFORE EXECUTED 
2] COMPILER ANALYZE THE CODE AND GERERATES A EXECUTABLE FILE which is EXECUTED by cpu
3] faster and more optimized c c++ java





name age course                     name age course 




select name from t1 inner join t2 on t1.age =t2.age 