#include <bits/stdc++.h>

using namespace std;

int dnfsort(int arr[], int n){


    int i=0;
    int mid=0;
    int j= n-1;


    while(mid<=high){


  if(arr[mid==0]){

    swap(arr[low],arr[mid]);
    low++;mid++;

  }else if (arr[mid]==1)
  {mid++;
    
  }else
  {
    swap(high,mid);
    mid++;high--;
  }
  
  


    }
}







int
int main(){



int n;
cin>>n;

int arr[n];

for(int i=0;i<n;i++){



    cin>>arr[i];

}

dnfsort(arr,n);



//it is know as deutch national f;ag sort 
// exapmle is sort arr contwaning numbers  0 1 2 // only 3 nubbers is repeted number of times



}