
//                1           ----level 1
 //             /    \    
//             /      \
//             2        0   --------level 2
//           /  \      /   \
//          3   4    6     7 -------leval 3

// 3 2 4 1 6 0 7

// LEFT SUBTREE 
// ROOT
//RIGHT SUBTREE

// NOTE : PREPRDER INORDER POST ORDER IS FORM OF DEPTH FIRST SEARCH TRAVERSAL
// LEVEL ORDER TRAVERSAL IS BREATH FIRST SERACH TRAVERSAL