//                1           ----level 1
 //             /    \    
//             /      \
//             2        0    --------level 2
//           /  \      /   \
//          3    4    6     7 -------leval 3

// 1 2 3 4 0 6 7 

// ROOT 
//LEFT SUBTREE
//RIGHT SUBTREE


// NOTE : PREPRDER INORDER POST ORDER IS FORM OF DEPTH FIRST SEARCH TRAVERSAL
// LEVEL ORDER TRAVERSAL IS BREATH FIRST SERACH TRAVERSAL